title: MAMC Notice Board
email: www.mamc@gmail.com
timezone: Asia/Dhaka
description: >-
  মির্জা আব্বাস মহিলা কলেজ নোটিশ বোর্ড

url: https://mamc-college.github.io
github_username:  mamc-admin
logo: /favicon.png
permalink: /:categories/:year/:month/:day/:title
markdown: kramdown
remote_theme: mmistakes/so-simple-theme
skin: /assets/css/skins/dark.css
paginate: 10  # amount of posts to show per page
paginate_path: /page:num/
category_archive_path: /categories/#
tag_archive_path: /tags/#
search_full_content: false
mathjax:
  enable: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

defaults:
  # Post defaults
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
      share: true

feed:
  path: atom.xml

liquid:
  error_mode: strict

google_fonts:
  - name: "Noto Sans"
    weights: "400,400b,700,700b"

author:
  name: MAMC Admin
  picture: /favicon.png
  email: www.mamc@gmail.com
  links:
    - title: Mail
      url: mailto:www.mamc@gmail.com
      icon: fas fa-at
    - title: Facebook
      url: https://www.facebook.com/Mirza-Abbas-Mohila-Degree-College-1979970975582543
      icon: fab fa-facebook-square

footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
