title: MAMC Notice Board
email: www.mamc@gmail.com
timezone: Asia/Dhaka
description: >-
  মির্জা আব্বাস মহিলা কলেজ নোটিশ বোর্ড

url: https://mamc-college.github.io
github_username:  mamc-admin

markdown: kramdown
remote_theme: "ahmubashshir/so-simple-theme@devel"
skin: "/assets/css/skins/dark.css"
paginate: 10
paginate_path: /:num/
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"
search_full_content: false
mathjax:
  enable: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

feed:
  path: atom.xml

liquid:
  error_mode: strict

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

author:
  name: MAMC Admin
  picture: /favicon.png
  email: www.mamc@gmail.com
  links:
    - title: Mail
      url: mailto:www.mamc@gmail.com
      icon: fad fa-at

footer_links:
  - title: Feed
    url: atom.xml
    icon: fad fa-rss-square
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
